### ISSUE TITLE
PageCap

### ISSUE THREAD

**Issue by SarahKhader** [moinmoti/Waffle#1]
Can I ask you how did you determine the parameter value PageCap to be 204?

constexpr unsigned int PAGECAP = 204;

**Comment by moinmoti** [comment]
A 2D data-point is expected to be of size 20 bytes (4×4 bytes for the minimum bounding rectangle + 4 bytes for an integer ID). Then, a 4 KiB page size would yield a capacity of 204 data-points per page.
